

# @server = http://pr.zarrtechnologies.com/{{PPROJECT}}/api/web

@server = http://localhost:8888/projects/zarrcom-backend/api/web

### Getting by category
GET {{server}}/advertisementbanners

### Getting selected fields
GET {{server}}/advertisementbanners?fields=key,value


### Mixed Queries
GET {{server}}/advertisementbanners?fields=key,value&BannersSearch[module_name]=frontend


###

GET {{server}}/advertisementbanners?BannersSearch[category]=Homepage%20Banners