
# @server = http://pr.zarrtechnologies.com/{{PPROJECT}}/api/web

###
# @server = http://pillsgo.com/backend/api/web
# @server = http://lacreativity.in/backend/api/web
# @server = http://faizark.com/backend/api/web

# @server = http://localhost:8888/projects/zarrcom-backend/api/web

@server = http://pr.zarrtechnologies.com/avon-backend/api/web

###

# @name login
POST {{server}}/customers/login
content-type: application/json

{
    "username": "7411343971",
    "password": "12345678"
}

### Getting setting by category
GET {{server}}/notifications?sort=-id&per-page=1000&page=1
Authorization: Bearer {{login.response.body.token}}

###

