# @server = http://localhost:8888/projects/zarrcom-backend/api/web
# @server = http://pr.zarrtechnologies.com/{{PPROJECT}}/api/web

@server = https://lacreativity.in/backend/api/web
###

# @name login
POST {{server}}/customers/login
content-type: application/json

{
    "username": "917411343971",
    "password": "12345678"
}

###

POST {{server}}/product_reviews
content-type: application/json
Authorization: Bearer {{login.response.body.token}}

{
    "product_id": 1,
    "review": "hhhhzzz",
    "rating_value": 3
}

###

GET {{server}}/product_reviews?product_id=1
Authorization: Bearer {{login.response.body.token}}